config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :categories, only: [:index, :new, :create, :destroy] do
    resources :entities, only: [:index, :new, :create, :destroy]
  end

  devise_scope :user do

    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root "home#index", as: :unauthenticated_root
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true, length: { maximum: 500 }

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :category
  belongs_to :entity
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: 'author_id'
  has_many :categories

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new, alert: 'Error, Failer creating category'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @entity = Entity.new
    @categories = Category.created_by_current_user(current_user)
  end

  def index
    @entities = Entity.all
    @category = Category.find(params[:category_id])
    @total = @category.entities.sum(:amount)
  end

  def create
    params = entity_params
    @entity = Entity.create(entity_params)
    @entity.author = current_user
    @categories_ids = params[:categories_ids]

    @categories_ids&.each do |id|
      category = Category.find(id) unless id == ''
      @entity.categories.push(category) unless category.nil?
    end

    if @entity.save
      category_id = @entity.categories.first.id if @entity.categories.first
      redirect_to category_entities_path(category_id), notice: 'Transaction added successfully'
    else
      render :new
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, category_ids: [])
  end

  def create_general_category
    @general = current_user.categories.where(name: 'General').first

    if @general.nil?
      @general = Category.create(name: 'General',
                                 icon: 'https://icons8.com/icon/SUtMjRvQFq1J/exchange', author: current_user)
    end

    @general
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/categories/index.html.erb
<main class="categories-container">
    <h2 class="categories-title">Categories</h2>
    <% if @categories.empty? %>
     <div class="empty-category">
        <h3>You don't have any categories yet!</h3>
        <%= link_to 'Add Category', new_category_path %>
     </div>
    <% else %>
        <div class="categories-card">
            <% @categories.each do |category| %>
            <div class="category">
                <img src="<%= category.icon %>" alt="category icon" class="category-img" >
                <div class="category-details">
                
                        <%= link_to category.name, category_entities_path(category), class: 'category-name' %>
                    
                    <span>
                        <%= category.created_at.strftime("%d %b %Y") %>
                    </span>
                </div>
                <div class="category-amount">
                        <Span>
                            $<%= category.entities.inject(0) { |sum, e| sum += e.amount  }%> 
                        </Span>
                    </div>
            </div>
            <% end %>
            <div class="add-btn-container">
            <%= link_to 'Add Category', new_category_path, class: 'add-btn' %>
            </div>
        </div>
    <% end %>
</main>

app/views/categories/new.html.erb
<main>
<div class="new-category-nav">
<%= render "shared/back" %>
<h3 class="new-category-title">New Category</h3>
</div>

<%= form_with(model: Category, url: categories_path, method: :post) do |f| %>

    <div class="field">
        <%= f.text_field :name, placeholder: 'Enter category name' %>
    </div>

    <div class="field">
        <%= f.text_field :icon, placeholder: 'Paste icon url'%>
    </div>
    <div class="save-btn-container">
    <%= f.submit 'Save', class: 'add-btn' %> <br>
    </div>
<% end %>
</main>

app/views/entities/index.html.erb
<div class="new-category-nav">
<%= render "shared/back" %>
<h3 class="new-category-title">Transactions</h3>
</div>
<main class="transactions-container">
    <% if @entities.empty? %>
    <div class="empty-category">
        <h3>You don't have any transactions yet! <%= @category.name %> Category</h3>
        <%= link_to 'Add a new transaction', new_category_entity_path %>
    </div>
<% else %>
    <div class="total-transactions">
        <span>
            <%= @category.name %>
        </span>
        <Span>
            $<%= @entities.inject(0) { |sum, e| sum += e.amount  }%> 
        </Span>
    </div>
    <div class="transactions">
        <% @entities.each do |entity| %>
            <div class="transaction">
                    <%= image_tag(@category.icon || '', class: "category-img") %>
                <div>
                    <h2>
                        <%= entity.name %>
                    </h2>
                    <span>
                        <%= entity.created_at.strftime("%d %b %Y") %>
                    </span>
                </div>
                <div>
                    <Span>
                        $<%= entity.amount %> 
                    </Span>
                </div>

                    </div>
                    <% end %>
                    </div>
                <%= link_to 'Add new transaction', new_category_entity_path, class: 'add-transaction-btn' %>
            <% end %>

</main>

app/views/entities/new.html.erb
<%= render "shared/back" %>
<main class="add-transactions-container">
    <h3>Add new Transactions</h3>

    <%= form_with(model: @entity, url: category_entities_path, method: :post) do |f| %>

        <div>
            <%= f.text_field :name, placeholder: 'Enter Transaction name' %>
        </div>

        <div>
            <%= f.number_field :amount, step: 1, placeholder: 'How much did you spend' %>
        </div>

        <% if @categories %>
        <div class="checkboxes-container">
            <%= f.label :categories, class: 'categories' %>
            <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| %>
                <div class="checkboxes">
                <div>
                <%= b.check_box %>
                </div>
                <div>
                <%= b.label %>
                </div>
                </div>
            <% end %>
        </div>
        <% end %>
            <%= f.submit 'Save', class: 'add-transaction-btn' %>

    <% end %>
</main>

app/views/home/index.html.erb
 <section class="splash-screen">
    <div class="logo-container">
     <h1 class="logo">BudgetWise</h1>
    </div>
     <div class="signs-container">
      <%= link_to 'LOG IN',  new_user_session_path, class: 'login-link' %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'signup-link' %>
     </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetWise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_back.html.erb
<a href="/" class="back-btn">
<%= image_tag 'back-btn.png', class: 'back-btn' %>
</a>